In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
df = pd.read_csv("Churn_Modelling.csv")
X = df.iloc[:, 3:-1].values
y = df.iloc[:,-1].values

In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder="passthrough")
X = np.array(ct.fit_transform(X))

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Initializing the ANN

In [7]:
ann = tf.keras.models.Sequential()

## Adding the input layer and the first hidden layer

In [8]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

## Adding the output layer

In [9]:
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

In [10]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])

In [11]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 3s 348us/sample - loss: 0.6049 - accuracy: 0.7034
Epoch 2/100
8000/8000 [==============================] - 1s 91us/sample - loss: 0.4691 - accuracy: 0.7972
Epoch 3/100
8000/8000 [==============================] - 1s 135us/sample - loss: 0.4501 - accuracy: 0.7972
Epoch 4/100
8000/8000 [==============================] - 1s 111us/sample - loss: 0.4415 - accuracy: 0.7979
Epoch 5/100
8000/8000 [==============================] - 1s 95us/sample - loss: 0.4364 - accuracy: 0.8015
Epoch 6/100
8000/8000 [==============================] - 1s 89us/sample - loss: 0.4321 - accuracy: 0.8049
Epoch 7/100
8000/8000 [==============================] - 1s 89us/sample - loss: 0.4260 - accuracy: 0.8079
Epoch 8/100
8000/8000 [==============================] - 1s 93us/sample - loss: 0.4176 - accuracy: 0.8105
Epoch 9/100
8000/8000 [==============================] - 1s 92us/sample - loss: 0.4081 - accuracy: 0.8135
Epoch 10/100
8000/800

8000/8000 [==============================] - 1s 85us/sample - loss: 0.3374 - accuracy: 0.8622s - loss: 0.3344 - accuracy
Epoch 77/100
8000/8000 [==============================] - 1s 82us/sample - loss: 0.3374 - accuracy: 0.8611
Epoch 78/100
8000/8000 [==============================] - 1s 87us/sample - loss: 0.3374 - accuracy: 0.8622
Epoch 79/100
8000/8000 [==============================] - 1s 83us/sample - loss: 0.3374 - accuracy: 0.8620
Epoch 80/100
8000/8000 [==============================] - 1s 84us/sample - loss: 0.3370 - accuracy: 0.8614
Epoch 81/100
8000/8000 [==============================] - 1s 83us/sample - loss: 0.3373 - accuracy: 0.8621
Epoch 82/100
8000/8000 [==============================] - 1s 86us/sample - loss: 0.3369 - accuracy: 0.8619
Epoch 83/100
8000/8000 [==============================] - 1s 82us/sample - loss: 0.3370 - accuracy: 0.8622
Epoch 84/100
8000/8000 [==============================] - 1s 82us/sample - loss: 0.3362 - accuracy: 0.8627
Epoch 85/100
8000/8000 

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

In [12]:
ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5

array([[False]])

In [13]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1532   53]
 [ 214  201]]


0.8665